package br.com.unirio.cr.data.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ESTUDANTE.
 */
public class Estudante {

    private Long id;
    private Long matricula;
    private Long cargaDoCurso;
    private Long cargaCumprida;
    private Double cargaAcumulada;

    public Estudante() {
    }

    public Estudante(Long id) {
        this.id = id;
    }

    public Estudante(Long id, Long matricula, Long cargaDoCurso, Long cargaCumprida, Double cargaAcumulada) {
        this.id = id;
        this.matricula = matricula;
        this.cargaDoCurso = cargaDoCurso;
        this.cargaCumprida = cargaCumprida;
        this.cargaAcumulada = cargaAcumulada;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMatricula() {
        return matricula;
    }

    public void setMatricula(Long matricula) {
        this.matricula = matricula;
    }

    public Long getCargaDoCurso() {
        return cargaDoCurso;
    }

    public void setCargaDoCurso(Long cargaDoCurso) {
        this.cargaDoCurso = cargaDoCurso;
    }

    public Long getCargaCumprida() {
        return cargaCumprida;
    }

    public void setCargaCumprida(Long cargaCumprida) {
        this.cargaCumprida = cargaCumprida;
    }

    public Double getCargaAcumulada() {
        return cargaAcumulada;
    }

    public void setCargaAcumulada(Double cargaAcumulada) {
        this.cargaAcumulada = cargaAcumulada;
    }

}
