package br.com.unirio.cr.data.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MATERIA.
 */
public class Materia {

    private Long id;
    private Long creditos;
    private String nome;

    public Materia() {
    }

    public Materia(Long id) {
        this.id = id;
    }

    public Materia(Long id, Long creditos, String nome) {
        this.id = id;
        this.creditos = creditos;
        this.nome = nome;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreditos() {
        return creditos;
    }

    public void setCreditos(Long creditos) {
        this.creditos = creditos;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

}
