package br.com.unirio.cr.data.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PERIODO.
 */
public class Periodo {

    private Long id;
    private Long matricula;
    private Integer numero;
    private Double nota;
    private Long creditosPeriodo;

    public Periodo() {
    }

    public Periodo(Long id) {
        this.id = id;
    }

    public Periodo(Long id, Long matricula, Integer numero, Double nota, Long creditosPeriodo) {
        this.id = id;
        this.matricula = matricula;
        this.numero = numero;
        this.nota = nota;
        this.creditosPeriodo = creditosPeriodo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMatricula() {
        return matricula;
    }

    public void setMatricula(Long matricula) {
        this.matricula = matricula;
    }

    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    public Double getNota() {
        return nota;
    }

    public void setNota(Double nota) {
        this.nota = nota;
    }

    public Long getCreditosPeriodo() {
        return creditosPeriodo;
    }

    public void setCreditosPeriodo(Long creditosPeriodo) {
        this.creditosPeriodo = creditosPeriodo;
    }
}
